spring.application.name=spring_application_dao
###################### 로그레벨설정				#######################

###################### DataSource Configuration #######################
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@124.198.47.195:1521:xe
spring.datasource.username=jdeveloper00
spring.datasource.password=jdeveloper00
###################### MyBatis설정 				#######################
mybatis.configuration.map-underscore-to-camel-case=true